apiVersion: v1
kind: Secret
metadata:
  name: ngo-service-secret
  namespace: solidarytech
  labels:
    app: ngo-service
type: Opaque
stringData:
  DATABASE_URL: "postgres://app:CHANGE-ME@CHANGE-ME.rds.amazonaws.com:5432/ngo_db"
