apiVersion: v1
kind: ConfigMap
metadata:
  name: donation-service-config
  namespace: solidarytech
  labels:
    app: donation-service
data:
  PORT: "8082"
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "CHANGE-ME"
