apiVersion: v1
kind: Secret
metadata:
  name: donation-service-secret
  namespace: solidarytech
  labels:
    app: donation-service
type: Opaque
stringData:
  DATABASE_URL: "postgres://app:CHANGE-ME@CHANGE-ME.rds.amazonaws.com:5432/donation_db"
