apiVersion: v1
kind: ConfigMap
metadata:
  name: volunteer-service-config
  namespace: solidarytech
  labels:
    app: volunteer-service
data:
  PORT: "8083"
  AWS_REGION: "us-east-1"
  AWS_DYNAMODB_TABLE: "SolidaryTechVolunteers"
